### ISSUE TITLE
S3 org job failure

### ISSUE THREAD

**Issue by rivernews** [rivernews/slack-middleware-server#43]
We observe error, looks like happened in travis scraper, something related to S3

```
gdOrgReviewScraperJob 2  progress 1
gdOrgReviewSupervisorJob drained
gdOrgReviewSupervisorJob drained
gdOrgReviewScraperJob drained
gdOrgReviewScraperJob drained
job 4 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-HealthCrowd-EI_IE755450.11,22.htm:0
job 4 preflight received [ 'BeginPubsubCommunication' ]
gdOrgReviewScraperJob 4  progress 2
job 4 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-HealthCrowd-EI_IE755450.11,22.htm:0
job 4 ignoring messages that are not for us preflight:scraper:acknowledged
job 3 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm:0
job 3 preflight received [ 'BeginPubsubCommunication' ]
job 3 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm:0
gdOrgReviewScraperJob 3  progress 2
job 3 ignoring messages that are not for us preflight:scraper:acknowledged
job 5 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Pinterest-EI_IE503467.11,20.htm:0
job 5 preflight received [ 'BeginPubsubCommunication' ]
job 5 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Pinterest-EI_IE503467.11,20.htm:0
job 5 ignoring messages that are not for us preflight:scraper:acknowledged
gdOrgReviewScraperJob 5  progress 2
job 1 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm:0
job 1 preflight received [ 'BeginPubsubCommunication' ]
job 1 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm:0
job 1 ignoring messages that are not for us preflight:scraper:acknowledged
gdOrgReviewScraperJob 1  progress 2
job 2 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-DigitalOcean-EI_IE823482.11,23.htm:0
job 2 preflight received [ 'BeginPubsubCommunication' ]
gdOrgReviewScraperJob 2  progress 2
job 2 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-DigitalOcean-EI_IE823482.11,23.htm:0
job 2 ignoring messages that are not for us preflight:scraper:acknowledged
job 3 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm:0
job 3 scraper job reported error, payload:Exception: A conflicting conditional operation is currently in progress against this resource. Please try again. (Service: S3, Status Code: 409, Request ID: 25F240197E1F1AA7)
unsubscribed channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm:0 successfully, org: https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm
supervisorJob interrupted due to error
 Error: job 3 scraper job reported error, payload:Exception: A conflicting conditional operation is currently in progress against this resource. Please try again. (Service: S3, Status Code: 409, Request ID: 25F240197E1F1AA7)
    at Queue.onFailed (/usr/src/node_modules/bull/lib/job.js:473:18)
    at Queue.emit (events.js:321:20)
    at Redis.<anonymous> (/usr/src/node_modules/bull/lib/queue.js:432:14)
    at Redis.emit (events.js:321:20)
    at DataHandler.handleSubscriberReply (/usr/src/node_modules/ioredis/built/DataHandler.js:80:32)
    at DataHandler.returnReply (/usr/src/node_modules/ioredis/built/DataHandler.js:47:18)
    at JavascriptRedisParser.returnReply (/usr/src/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/usr/src/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/usr/src/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (events.js:321:20) remaining orgList not yet finished (including failed one): [
  'https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm',
  'https://www.glassdoor.com/Overview/Working-at-Apple-EI_IE1138.11,16.htm',
  'https://www.glassdoor.com/Overview/Working-at-Dell-Technologies-EI_IE1327.11,28.htm'
]
gdOrgReviewScraperJob 3 failed Error: job 3 scraper job reported error, payload:Exception: A conflicting conditional operation is currently in progress against this resource. Please try again. (Service: S3, Status Code: 409, Request ID: 25F240197E1F1AA7)
    at /usr/src/node_modules/bull/lib/process/master.js:74:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  message: 'job 3 scraper job reported error, payload:Exception: A conflicting conditional operation is currently in progress against this resource. Please try again. (Service: S3, Status Code: 409, Request ID: 25F240197E1F1AA7)'
}
closing ioredis client
closing ioredis client
closing ioredis client
closing ioredis client
closing ioredis client
closing ioredis client
gdOrgReviewSupervisorJob 1 failed Error: job 3 scraper job reported error, payload:Exception: A conflicting conditional operation is currently in progress against this resource. Please try again. (Service: S3, Status Code: 409, Request ID: 25F240197E1F1AA7)
    at Queue.onFailed (/usr/src/node_modules/bull/lib/job.js:473:18)
    at Queue.emit (events.js:321:20)
    at Redis.<anonymous> (/usr/src/node_modules/bull/lib/queue.js:432:14)
    at Redis.emit (events.js:321:20)
    at DataHandler.handleSubscriberReply (/usr/src/node_modules/ioredis/built/DataHandler.js:80:32)
    at DataHandler.returnReply (/usr/src/node_modules/ioredis/built/DataHandler.js:47:18)
    at JavascriptRedisParser.returnReply (/usr/src/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/usr/src/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/usr/src/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (events.js:321:20) {
  message: 'job 3 scraper job reported error, payload:Exception: A conflicting conditional operation is currently in progress against this resource. Please try again. (Service: S3, Status Code: 409, Request ID: 25F240197E1F1AA7)'
}
s3OrgsJob drained
s3OrgsJob 1 failed Error: job 3 scraper job reported error, payload:Exception: A conflicting conditional operation is currently in progress against this resource. Please try again. (Service: S3, Status Code: 409, Request ID: 25F240197E1F1AA7)
    at Queue.onFailed (/usr/src/node_modules/bull/lib/job.js:473:18)
    at Queue.emit (events.js:333:22)
    at Redis.<anonymous> (/usr/src/node_modules/bull/lib/queue.js:432:14)
    at Redis.emit (events.js:321:20)
    at DataHandler.handleSubscriberReply (/usr/src/node_modules/ioredis/built/DataHandler.js:80:32)
    at DataHandler.returnReply (/usr/src/node_modules/ioredis/built/DataHandler.js:47:18)
    at JavascriptRedisParser.returnReply (/usr/src/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/usr/src/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/usr/src/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (events.js:321:20) {
  message: 'job 3 scraper job reported error, payload:Exception: A conflicting conditional operation is currently in progress against this resource. Please try again. (Service: S3, Status Code: 409, Request ID: 25F240197E1F1AA7)'
}
job 4 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-HealthCrowd-EI_IE755450.11,22.htm:0
job 4 progress reported {
  processed: 0,
  wentThrough: 6,
  total: 10,
  elapsedTimeString: '*00:00:18.25*'
}
gdOrgReviewScraperJob 4  progress 60
job 1 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm:0
job 1 scraper job reported error, payload:Exception: / by zero
unsubscribed channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm:0 successfully, org: https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm
gdOrgReviewScraperJob 1 failed Error: job 1 scraper job reported error, payload:Exception: / by zero
    at /usr/src/node_modules/bull/lib/process/master.js:74:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  message: 'job 1 scraper job reported error, payload:Exception: / by zero'
}
supervisorJob interrupted due to error
 Error: job 1 scraper job reported error, payload:Exception: / by zero
    at Queue.onFailed (/usr/src/node_modules/bull/lib/job.js:473:18)
    at Queue.emit (events.js:321:20)
    at Redis.<anonymous> (/usr/src/node_modules/bull/lib/queue.js:432:14)
    at Redis.emit (events.js:321:20)
    at DataHandler.handleSubscriberReply (/usr/src/node_modules/ioredis/built/DataHandler.js:80:32)
    at DataHandler.returnReply (/usr/src/node_modules/ioredis/built/DataHandler.js:47:18)
    at JavascriptRedisParser.returnReply (/usr/src/node_modules/ioredis/built/DataHandler.js:21:22)
    at JavascriptRedisParser.execute (/usr/src/node_modules/redis-parser/lib/parser.js:544:14)
    at Socket.<anonymous> (/usr/src/node_modules/ioredis/built/DataHandler.js:25:20)
    at Socket.emit (events.js:321:20) remaining orgList not yet finished (including failed one): [
  'https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm'
]
closing ioredis client
closing ioredis client
closing ioredis client
job 5 received message from channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Pinterest-EI_IE503467.11,20.htm:0
job 5 progress reported {
  processed: 0,
  wentThrough: 7,
  total: 257,
  elapsedTimeString: '*00:00:17.617*'
}
^C
```

## Other issue: drained jobs

```
KUBECONFIG=kubeconfig.yaml kubectl -n slack-middleware-service logs --follow deploy/slack-middleware-service-deployment
Running on http://localhost:8002
created ioredis client, total 1
created ioredis client, total 2
initialized job queue for gdOrgReviewScraperJob
initialized job queue for gdOrgReviewSupervisorJob
initialized job queue for s3OrgsJob
registered job queues to job UI dashboard [ 'gdOrgReviewSupervisorJob', 'gdOrgReviewScraperJob', 's3OrgsJob' ]
created ioredis client, total 3
created ioredis client, total 4
created ioredis client, total 5
s3OrgsJobController: existing s3 job count 0, ready to dispatch job
s3OrgsJob 1 waiting
s3OrgsJob 1 active
s3OrgsJob 1 started {
  id: '1',
  name: '__default__',
  data: {},
  opts: { attempts: 1, delay: 0, timestamp: 1583733555261 },
  progress: [Function (anonymous)],
  delay: 0,
  timestamp: 1583733555261,
  attemptsMade: 0,
  stacktrace: [],
  returnvalue: null,
  finishedOn: null,
  processedOn: 1583733555294,
  log: [Function (anonymous)]
}
created ioredis client, total 1
created ioredis client, total 2
initialized job queue for gdOrgReviewSupervisorJob
about to list url objects on s3...
created ioredis client, total 3
S3 list url objects: If got continue token, will request next page. ContinuationToken is undefined
orgInfoListBucket [
  [
    'https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm',
    'https://www.glassdoor.com/Overview/Working-at-Apple-EI_IE1138.11,16.htm',
    'https://www.glassdoor.com/Overview/Working-at-Dell-Technologies-EI_IE1327.11,28.htm'
  ],
  [
    'https://www.glassdoor.com/Overview/Working-at-DigitalOcean-EI_IE823482.11,23.htm',
    'https://www.glassdoor.com/Overview/Working-at-Ford-Motor-Company-EI_IE263.11,29.htm',
    'https://www.glassdoor.com/Overview/Working-at-Google-EI_IE9079.11,17.htm'
  ],
  [
    'https://www.glassdoor.com/Overview/Working-at-HealthCrowd-EI_IE755450.11,22.htm',
    'https://www.glassdoor.com/Overview/Working-at-Hewlett-Packard-Enterprise-HPE-EI_IE1093046.11,41.htm',
    'https://www.glassdoor.com/Overview/Working-at-Microsoft-EI_IE1651.11,20.htm'
  ],
  [
    'https://www.glassdoor.com/Overview/Working-at-Pinterest-EI_IE503467.11,20.htm',
    'https://www.glassdoor.com/Overview/Working-at-SAP-Concur-EI_IE8763.11,21.htm',
    'https://www.glassdoor.com/sap'
  ],
  [
    'https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm'
  ]
]
s3OrgsJob 1  progress 1
gdOrgReviewSupervisorJob 2 active
gdOrgReviewSupervisorJob 1 waiting
gdOrgReviewSupervisorJob 2 waiting
gdOrgReviewSupervisorJob 3 waiting
gdOrgReviewSupervisorJob 4 waiting
gdOrgReviewSupervisorJob 5 waiting
gdOrgReviewSupervisorJob 1 active
gdOrgReviewSupervisorJob 3 active
gdOrgReviewSupervisorJob 5 active
gdOrgReviewSupervisorJob 4 active
supervisorJob started processing, with params {
  orgInfoList: [
    'https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm'
  ]
}
created ioredis client, total 1
created ioredis client, total 2
initialized job queue for gdOrgReviewScraperJob
gdOrgReviewSupervisorJob 5  progress 1
supervisorJob will dispatch scraper jobs
supervisorJob added scraper job 1
gdOrgReviewScraperJob 1 waiting
gdOrgReviewScraperJob 1 active
created ioredis client, total 3
supervisorJob started processing, with params {
  orgInfoList: [
    'https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm',
    'https://www.glassdoor.com/Overview/Working-at-Apple-EI_IE1138.11,16.htm',
    'https://www.glassdoor.com/Overview/Working-at-Dell-Technologies-EI_IE1327.11,28.htm'
  ]
}
supervisorJob started processing, with params {
  orgInfoList: [
    'https://www.glassdoor.com/Overview/Working-at-DigitalOcean-EI_IE823482.11,23.htm',
    'https://www.glassdoor.com/Overview/Working-at-Ford-Motor-Company-EI_IE263.11,29.htm',
    'https://www.glassdoor.com/Overview/Working-at-Google-EI_IE9079.11,17.htm'
  ]
}
created ioredis client, total 1
created ioredis client, total 2
created ioredis client, total 1
initialized job queue for gdOrgReviewScraperJob
created ioredis client, total 2
gdOrgReviewSupervisorJob 2  progress 1
initialized job queue for gdOrgReviewScraperJob
supervisorJob will dispatch scraper jobs
gdOrgReviewSupervisorJob 1  progress 1
supervisorJob started processing, with params {
  orgInfoList: [
    'https://www.glassdoor.com/Overview/Working-at-Pinterest-EI_IE503467.11,20.htm',
    'https://www.glassdoor.com/Overview/Working-at-SAP-Concur-EI_IE8763.11,21.htm',
    'https://www.glassdoor.com/sap'
  ]
}
created ioredis client, total 1
supervisorJob will dispatch scraper jobs
created ioredis client, total 2
initialized job queue for gdOrgReviewScraperJob
supervisorJob started processing, with params {
  orgInfoList: [
    'https://www.glassdoor.com/Overview/Working-at-HealthCrowd-EI_IE755450.11,22.htm',
    'https://www.glassdoor.com/Overview/Working-at-Hewlett-Packard-Enterprise-HPE-EI_IE1093046.11,41.htm',
    'https://www.glassdoor.com/Overview/Working-at-Microsoft-EI_IE1651.11,20.htm'
  ]
}
created ioredis client, total 1
gdOrgReviewSupervisorJob 4  progress 1
created ioredis client, total 2
initialized job queue for gdOrgReviewScraperJob
gdOrgReviewSupervisorJob 3  progress 1
supervisorJob will dispatch scraper jobs
supervisorJob will dispatch scraper jobs
gdOrgReviewScraperJob 2 active
supervisorJob added scraper job 2
gdOrgReviewScraperJob 2 waiting
created ioredis client, total 3
supervisorJob added scraper job 3
gdOrgReviewScraperJob 3 active
gdOrgReviewScraperJob 3 waiting
created ioredis client, total 3
supervisorJob added scraper job 4
gdOrgReviewScraperJob 4 active
gdOrgReviewScraperJob 4 waiting
supervisorJob added scraper job 5
gdOrgReviewScraperJob 5 active
gdOrgReviewScraperJob 5 waiting
created ioredis client, total 3
created ioredis client, total 3
scraper job 1 started processing, with params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm'
}
scraper job 1 patched params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm'
}
created redis client, total 1
created redis client, total 2
scraper job 5 started processing, with params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-Pinterest-EI_IE503467.11,20.htm'
}
job 1 subscribed to channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Salesforce-EI_IE11159.11,21.htm:0, count 1
job 1 subscribed to channel scraperAdmin, count 2
scraper job 5 patched params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-Pinterest-EI_IE503467.11,20.htm'
}
created redis client, total 1
created redis client, total 2
job 5 subscribed to channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Pinterest-EI_IE503467.11,20.htm:0, count 1
job 5 subscribed to channel scraperAdmin, count 2
scraper job 4 started processing, with params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-HealthCrowd-EI_IE755450.11,22.htm'
}
scraper job 4 patched params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-HealthCrowd-EI_IE755450.11,22.htm'
}
created redis client, total 1
created redis client, total 2
job 4 subscribed to channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-HealthCrowd-EI_IE755450.11,22.htm:0, count 1
job 4 subscribed to channel scraperAdmin, count 2
scraper job 3 started processing, with params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm'
}
scraper job 3 patched params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm'
}
scraper job 2 started processing, with params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-DigitalOcean-EI_IE823482.11,23.htm'
}
scraper job 2 patched params {
  orgInfo: 'https://www.glassdoor.com/Overview/Working-at-DigitalOcean-EI_IE823482.11,23.htm'
}
created redis client, total 1
created redis client, total 2
created redis client, total 1
created redis client, total 2
job 3 subscribed to channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-Amazon-EI_IE6036.11,17.htm:0, count 1
job 3 subscribed to channel scraperAdmin, count 2
job 2 subscribed to channel scraperJobChannel:https://www.glassdoor.com/Overview/Working-at-DigitalOcean-EI_IE823482.11,23.htm:0, count 1
job 2 subscribed to channel scraperAdmin, count 2
job 1 request travis job successfully: 313626612/pending, remaining_requests=50
gdOrgReviewScraperJob 1  progress 1
job 5 request travis job successfully: 313626613/pending, remaining_requests=50
gdOrgReviewScraperJob 5  progress 1
job 4 request travis job successfully: 313626614/pending, remaining_requests=48
gdOrgReviewScraperJob 4  progress 1
job 3 request travis job successfully: 313626615/pending, remaining_requests=47
gdOrgReviewScraperJob 3  progress 1
job 2 request travis job successfully: 313626616/pending, remaining_requests=47
gdOrgReviewScraperJob 2  progress 1
gdOrgReviewSupervisorJob drained
gdOrgReviewSupervisorJob drained
gdOrgReviewScraperJob drained
gdOrgReviewScraperJob drained
```

## What's going on right now?

Surviving jobs/supervisorjob still active. S3 org job is rejected by the first failed job.

**Comment by rivernews** [comment]
## Approaches

### S3 409 Error

- How about just 1 org: Maybe we can change s3 org fetch function to just return single org, deploy to production, and see if we still have such issue.
    - We can observe if it creates duplicate travis build, which will definitely be a problem.
- W/o re-creating queues in process?
- Lower the concurrency number?

**Comment by rivernews** [comment]
### 2nd Round

### Duplicated travis calls

Salesforce - we have two builds - [first](https://travis-ci.com/github/rivernews/review-scraper-java-development-environment/jobs/296746253) and after 4 min the [second](https://travis-ci.com/github/rivernews/review-scraper-java-development-environment/jobs/296746828).

### Error in scraper

[Healthcrowd failed](https://rivernews-cloud.slack.com/archives/CSZR6SNQJ/p1583885603032600).  

[SAP Concur also failed](https://rivernews-cloud.slack.com/archives/CSZR6SNQJ/p1583886004037900).

Both got this error (in bull dashboard):
```log
Error: job 18 scraper job reported error, payload:Exception: / by zero
    at /usr/src/node_modules/bull/lib/process/master.js:74:21
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by rivernews** [comment]
## Pressure Test Result

- [ ] Still observed many low went through rate
- [ ] Salesforce reported new "Content Block" review. Can we map the review to existing review?
- [ ] Other issues in slack reminder

**Comment by rivernews** [comment]
## Pressure test result 2

- [ ] Duplicated travis request problem occurs again. Don't know why it's been requested the second time. Might have to go into the log and find out.
- [ ] [Local review count = 0 on Dell](https://rivernews-cloud.slack.com/archives/CSZR6SNQJ/p1583910366084900). Maybe we should just parse the entore webpage source code.
- [ ] Also some supervisor timed out, while travis scraper was waiting them.
- [x] Memory usage seems find. While the first pulse where dispatching 18 jobs at once, we see memory usage surges from 33% to 44%, it still looks fine.

**Comment by rivernews** [comment]
### Toubleshooting Summary

### Re-attempting supervisor job issue

Which causes "channel locked" issue. We did add the lock. But shall not happening. By default Bull says no auto retrying. That's not true and our supervisorjob has `attempts=2`. Now we even set job option to `attempts=1`. The issue persists.

**Comment by rivernews** [comment]
After limiting registering process to only one (inside the master process), the job stalled issue is now gone.
